ozonecrm/urls.py
from django.conf.urls import patterns, include, url

from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url( r'^static/(?P<path>.*)$', 'django.views.static.serve',{ 'document_root': settings.STATIC_ROOT }),
    url(r"^media/(?P<path>.*)$","django.views.static.serve",{"document_root": settings.MEDIA_ROOT,}),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'crmapp/ulogin.html'}),
    # Examples:
    # url(r'^$', 'ozonecrm.views.home', name='home'),
    # url(r'^ozonecrm/', include('ozonecrm.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^logout/$','crmapp.views.ulogout'),
    url(r'^login/$','crmapp.views.ulogin'),
    url(r'^user_home/$','crmapp.views.user_home'),
    url(r'^write_mail/$','crmapp.views.write_mail'),
    url(r'^direct/(\d+)','crmapp.views.direct_user'),
    url(r'^show_info/(\d+)/(\d+)','crmapp.views.show_info'),
    url(r'^routing_install/(\d+)/(\d+)','crmapp.views.routing_install'),
    url(r'^user_add','crmapp.views.user_add'),
    url(r'^business_add','crmapp.views.business_add'),
    url(r'^routing_add','crmapp.views.routing_add'),
    url(r'^cooper_add','crmapp.views.cooper_add'),
    url(r'^tag_add','crmapp.views.tag_add'),
    url(r'^show_busy','crmapp.views.show_busy'),
    url(r'^show_router','crmapp.views.show_router'),
   # url(r'^index','crmapp.views.index'),
   # url(r'^regist','crmapp.views.regist'),
    url(r'^display_meta','crmapp.views.display_meta'),
)

crmapp/models.py
#coding:utf-8
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


CONDITION_CHOICES= (
     
     (u'---', u'---'),
     (u'not_installed', u'未安装'),
     (u'installed', u'已安装中'),
)

idtype=(
    (u'---', u'---'),
    (u'Administrator', u'管理员'),
    (u'installor', u'安装员'),
)
class UserMail(models.Model):
     send_name = models.CharField(max_length=30, verbose_name=u'发件人')
     content = models.TextField(verbose_name=u'信息内容')
     receive_name = models.CharField(max_length=30, verbose_name=u'收件人')
     pub_time = models.DateField(auto_now=True,verbose_name=u'发送时间')
     def __unicode__(self):
         return self.content
class Maintainer(models.Model):
    number = models.CharField(max_length=30, verbose_name='编号')
    name = models.CharField(max_length=30, verbose_name=u'姓名')
    phonenumber= models.IntegerField(max_length=200, verbose_name=u'手机号码')
    headImg = models.FileField(upload_to='./images', verbose_name=u'头像', blank=True)
    remarks = models.TextField(verbose_name=u'备注')
    identity = models.CharField(max_length=20, choices=idtype, verbose_name=u'身份')
    send_mail = models.ManyToManyField(UserMail, related_name='send_mail',verbose_name=u'发出的信息', blank=True, null=True)
    receive__mail = models.ManyToManyField(UserMail, related_name='receive_mail',verbose_name=u'发出的信息',blank=True, null=True)
    user = models.OneToOneField(User, blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'人员管理'
        verbose_name_plural = u'人员管理'
        ordering = ['number']
        permissions = (
        ('can_direct', 'can direct installor'),
        ('can_install', 'can install'),
        )


class Tag(models.Model):
    tag = models.CharField(max_length=30, verbose_name=u'经营内容')
    
    def __unicode__(self):
       return self.tag
    
    class Meta:
        verbose_name = u'经营内容'
        verbose_name_plural = u'经营内容'

class Business(models.Model):
    number = models.CharField(max_length=30,verbose_name=u'编号')
    name   = models.CharField(max_length=30, verbose_name=u'商家名称')
    shopname = models.CharField(max_length=30, verbose_name=u'门店名称')
    tag = models.ManyToManyField(Tag, verbose_name='经营内容')
    district = models.CharField(max_length=300, verbose_name=u'地区')
    address = models.CharField(max_length=300, verbose_name=u'地址')
    bmap = models.BooleanField(verbose_name=u'地图')
    remarks = models.CharField(max_length=150, verbose_name=u'备注')

    def __unicode__(self):
        return self.name 
    
    class Meta:
        verbose_name = u'商家管理'
        verbose_name_plural =u'商家管理'
        ordering = ['number']


class Routing(models.Model):
    number = models.CharField(max_length=30, verbose_name=u'路由编号')
    password = models.CharField(max_length=50, verbose_name=u'路由密码')
    mac = models.CharField(max_length=30, verbose_name=u'mac地址')
    ssid = models.CharField(max_length=30, verbose_name=u'ssid')
    condition = models.CharField(max_length=30, choices=CONDITION_CHOICES,verbose_name=u'状态')
    installor = models.ForeignKey(Maintainer, verbose_name=u'安装人员', related_name='installor',blank=True,null=True)
    installtime = models.DateField(verbose_name=u'安装时间',blank=True,null=True)
    remarks = models.CharField(max_length=30, verbose_name=u'备注')    
    business = models.ForeignKey(Business, verbose_name=u'商家', blank=True)
    
    def __unicode__(self):
        return self.ssid
    
    class Meta:
        verbose_name = u'路由信息'
        verbose_name_plural = u'路由信息'
        ordering = ['number']                                                                 
                                                                     
class CooperInfo(models.Model):
    number = models.CharField(max_length=30, verbose_name=u'合同编号')
    starttime = models.DateField(verbose_name=u'起始日期')
    endtime = models.DateField(verbose_name=u'结束日期')
    cooperImg = models.FileField(upload_to='./images/cooper', verbose_name=u'合作复印件')
    desc = models.TextField(verbose_name=u'商家描述')
    business = models.OneToOneField(Business, verbose_name=u'商家')
    
    def __unicode__(self):
        return self.number
    class Meta:
        verbose_name = u'合作信息'
        verbose_name_plural = u'合作信息'
        ordering = ['number']                                                                       

crmapp/views.py
# Create your views here.
#coding:utf-8
import datetime
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from crmapp.models import *
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
users = User.objects.all()


class LogForm(forms.Form):
    username = forms.CharField(label=u'账号',error_messages={'required':'请输入帐号'})
    password = forms.CharField(widget = forms.PasswordInput,label=u'密码',error_messages={'required':'请输入密码'})

class UserForm(forms.Form):
    number = forms.CharField(label=u'编号',error_messages={'required':'请输入编号'})
    username = forms.CharField(label=u'账号',error_messages={'required':'请输入帐号'})
    name = forms.CharField(label=u'姓名',error_messages={'required':'请输入名字'})
    password = forms.CharField(widget = forms.PasswordInput,label=u'密码',error_messages={'required':'请输入密码'})
    email = forms.EmailField(label=u'邮箱',error_messages={'required':'请输入邮箱'})
    phonenumber = forms.CharField(label=u'手机号码',error_messages={'required':'请输入手机号码'})
    headImg = forms.FileField(label=u'头像',required=False) 
    identity = forms.CharField(widget=forms.Select(choices=idtype), label=u'身份')
    remarks = forms.CharField(label=u'备注', required=False,widget = forms.Textarea)


class MailForm(forms.Form):
    content = forms.CharField(label=u'内容', widget = forms.Textarea)
    receive_name = forms.CharField(label=u'收件人')

class BusyForm(forms.Form):
    number = forms.CharField(label=u'商家编号',error_messages={'required':'请输入编号'})
    name =  forms.CharField(label=u'商家名字',error_messages={'required':'请输入商家名字'})
    shopname = forms.CharField(label=u'门店名字',error_messages={'required':'请输入门店名字'})
    queryset0 = Tag.objects.all()
    tag = forms.ModelChoiceField(queryset=queryset0,empty_label=None,label=u'经营内容',error_messages={'required':'请输入经营内容'})
    district = forms.CharField(label=u'地区',error_messages={'required':'请输入地区信息'})
    address = forms.CharField(label=u'详细地址',error_messages={'required':'请输入详细地址'})
    bmap = forms.BooleanField(label=u'是否有地图',error_messages={'required':'请选择'})
    queryset1 = Maintainer.objects.all()
    condition = forms.CharField(label=u'安装情况',error_messages={'required':'请选择安装状况'}, widget=forms.Select(choices=CONDITION_CHOICES))
    installor = forms.ModelChoiceField(queryset=queryset1,empty_label=None,label=u'安装人员',error_messages={'required':'请选择或添加安装人员'})
    installtime = forms.CharField(label=u'安装时间',error_messages={'required':'请输入安装时间'})
    remarks = forms.CharField(label=u'备注',required=False)

class RoutingForm(forms.Form):
    number = forms.CharField()
    gateway = forms.CharField()
    password = forms.CharField()
    mac = forms.CharField()
    ssid = forms.CharField()
    installor = forms.ModelChoiceField(queryset=Maintainer.objects.all(),empty_label=None)
    remarks = forms.CharField()
    queryset = Business.objects.all()
    business = forms.ModelChoiceField(queryset=queryset,empty_label=None)
    
         
class CooperForm(forms.Form):
    number = forms.CharField()
    starttime = forms.DateField()
    endtime = forms.DateField()
    cooperImg = forms.FileField()
    desc = forms.CharField(widget=forms.Textarea)
    queryset = Business.objects.all()
    business = forms.ModelChoiceField(queryset=queryset, empty_label=None)

class TagForm(forms.Form):
    tag = forms.CharField()

class DirForm(forms.Form):
    user = forms.ModelChoiceField(queryset=Maintainer.objects.all(),empty_label=None,label='指定安装人员')

def direct_user(request,id=None):
    router = Routing.objects.get(id=id)
    busy = router.business
    if request.method == 'POST':
        df = DirForm(request.POST)
        if df.is_valid():
            user = df.cleaned_data['user']
    else:
        df = DirForm()
    variables = RequestContext(request,{'df':df,'router':router,'busy':busy})
    return render_to_response('direct.html',variables)

def show_info(request, rid=None, uid=None):
    router = Routing.objects.get(id=rid)
    user = request.user
    return render_to_response('show_info.html',locals())
       
def routing_install(request, rid=None, uid=None):
    router = Routing.objects.get(id=rid)
    installor = Maintainer.objects.get(id=uid)
    if router:
        router.condition = "installed"
        router.installor = installor
        router.installtime = datetime.date.today()
        router.save()
        return HttpResponseRedirect('/show_router')
    return render_to_response('routinginstall.html',locals())


def ulogin(request):
    if request.method == 'POST':
        lf = LogForm(request.POST)
        if lf.is_valid():
            username = lf.cleaned_data['username']
            password = lf.cleaned_data['password']
            user = authenticate(username=username,password=password)
            if user:
                if user in users:
                    login(request,user)
                    return HttpResponseRedirect('/show_busy/')
            else:
                return HttpResponseRedirect('/ulogin')
    else:
        lf = LogForm()
    variables = RequestContext(request, {'lf':lf})
    return render_to_response('ulogin.html',variables)


def user_home(request):
    user = request.user
    return render_to_response('user_home.html',locals())


def write_mail(request):
    if request.method == 'POST':
        mf = MailForm(request.POST)
        if mf.is_valid():
            content = mf.cleaned_data['content'] 
            receive_name = mf.cleaned_data['receive_name']
          #  if receive_name = request.user.username or receive_name = request.user.maintainer.name:
          #     return HttpResponse('No!')
            user = User.objects.get(username=receive_name)
            if not user:
               return HttpResponse('No!')
            mail = UserMail.objects.create(
                send_name = request.user.username,
                content = content,
                receive_name = receive_name
            )
            user.maintainer.receive__mail.add(mail)
            request.user.maintainer.send_mail.add(mail)
    else:
        mf = MailForm()
    return render_to_response('write_mail.html',locals())                
@login_required    
def user_add(request):
    if request.method == 'POST':
        uf = UserForm(request.POST, request.FILES)
        if uf.is_valid():
            number = uf.cleaned_data['number']
            username = uf.cleaned_data['username']
            name = uf.cleaned_data['name']
            password = uf.cleaned_data['password']
            email = uf.cleaned_data['email']
            phonenumber = uf.cleaned_data['phonenumber']
            headImg = uf.cleaned_data['headImg']
            identity = uf.cleaned_data['identity']
            remarks = uf.cleaned_data['remarks']
            user = User.objects.create_user(username=username,password=password,email=email)
            Maintainer.objects.create(number=number, name=name, phonenumber=phonenumber, headImg=headImg, identity=identity, remarks=remarks, user=user)
            return HttpResponse('ok')
    else:
        uf = UserForm()
    variables = RequestContext(request, {'uf':uf})
    return render_to_response('user_add.html',variables)


@login_required    
def business_add(request):
   if request.method == "POST":
      bf = BusyForm(request.POST)
      if bf.is_valid():
          number = bf.cleaned_data['number']
          name = bf.cleaned_data['name']
          tag = bf.cleaned_data['tag']
          district = bf.cleaned_data['district']
          address = bf.cleaned_data['address']
          bmap = bf.cleaned_data['bmap']
          condition = bf.cleaned_data['condition']
          installor = bf.cleaned_data['installor']
          Maintainer.name = installor
          installor = Maintainer.name
          installtime = bf.cleaned_data['installtime']
          remarks = bf.cleaned_data['remarks']
          Business.objects.create(number=number, name=name, shopname=shopname, district=district, address=address\
          ,bmap=bmap, condition=condition, installor=adder, installtime=installtime, remarks=remarks)
          return HttpResponse('ok')
   else:
       bf = BusyForm()
   variables = RequestContext(request,{'bf':bf})
   return render_to_response('business_add.html',variables)

@login_required    
def routing_add(request):
    if request.method == "POST":
        rf = RoutingForm(request.POST)
        if rf.is_valid():
            number = rf.cleaned_data['number']
            password = rf.cleaned_data['password']
            mac = rf.cleaned_data['mac']
            ssid = rf.cleaned_data['ssid']
            remarks = rf.cleaned_data['remarks']
            business = rf.cleaned_data['business']
            Routing.objects.create(number=number, password=password, mac=mac, ssid=ssid, remarks=remarks, business=business)
    else:
        rf = RoutingForm()
    variables = RequestContext(request,{'rf':rf})
    return render_to_response('routing_add.html',variables)
  
@login_required    
def cooper_add(request):
   if request.method == "POST":
       cf = CooperForm(request.POST)
       if cf.is_valid():
           number = cf.cleaned_data['number']
           starttime = cf.cleaned_data['starttime']
           endtime = cf.cleaned_data['endtime']
           cooperImg = cf.cleaned_data['cooperImg']
           desc = cf.cleaned_data['desc']
           business = cf.cleaned_data['business']
           Business.name = business
           CooperInfo.objects.create(number=number, starttime=starttime, endtime=endtime, cooperImg=cooperImg, desc=desc, bussiness=Business.name)
   else:
       cf = CooperForm()
   variables = RequestContext(request,{'cf':cf})
   return render_to_response('cooper_add.html',variables)

@login_required    
def tag_add(request):
   if request.method == "POST":
       tf = TagForm(request)

crmapp/templates/business_add.html
<script>
function id_to_windowname(text) {
    text = text.replace(/\./g, '__dot__');
    text = text.replace(/\-/g, '__dash__');
    return text;
}

function showAddAnotherPopup(triggeringLink) {
    var name = triggeringLink.id.replace(/^add_/, '');
    name = id_to_windowname(name);
    href = triggeringLink.href
    //alert(href);
    if (href.indexOf('?') == -1) {
        href += '?_popup=1';
    } else {
        href  += '&_popup=1';
    }
    var win = window.open(href, name, 'height=500,width=800,resizable=yes,scrollbars=yes');
    win.focus();
    return false;
}
</script>
<form action="" method="POST"> {% csrf_token %}
<table>
{{bf.as_table}}
<a href="tag_add/" class="add-another" id="add_id_tag" onclick="return showAddAnotherPopup(this);">添加经营内容</a><br/>
<a href="user_add/" class="add-another" id="add_id_adder" onclick="return showAddAnotherPopup(this);">添加管理员</a><br/>
<a href="user_add/" class="add-another" id="add_id_installor" onclick="return showAddAnotherPopup(this);">添加安装员</a>
</table>
<input type="submit" value="确定">

</form>

crmapp/templates/cooper_add.html
<script>
function id_to_windowname(text) {
    text = text.replace(/\./g, '__dot__');
    text = text.replace(/\-/g, '__dash__');
    return text;
}

function showAddAnotherPopup(triggeringLink) {
    var name = triggeringLink.id.replace(/^add_/, '');
    name = id_to_windowname(name);
    href = triggeringLink.href
    //alert(href);
    if (href.indexOf('?') == -1) {
        href += '?_popup=1';
    } else {
        href  += '&_popup=1';
    }
    var win = window.open(href, name, 'height=500,width=800,resizable=yes,scrollbars=yes');
    win.focus();
    return false;
}
</script>
<form action="" method="post" enctype="multipart/form-data"> {% csrf_token %}
<table>
{{cf.as_table}}
<a href="business_add/" class="add-another" id="add_id_business" onclick="return showAddAnotherPopup(this);">商家</a><br/>
</table>
<input type="submit" value="确定">

</form>

crmapp/templates/direct.html
<form action="" method="POST"> {% csrf_token %}
<table>
{{df.as_table}}
路由:{{router}}<br />
商家:{{busy}}
</table>
<input type="submit" value="确定">
</form>

crmapp/templates/rinstall.html
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title></title>
</head>
<body>
<div id="user">{% csrf_token %}
username: <input type="text" id="rnumber" onkeydown="userlogin()"/>
{{rf.as_p}}
</div>
<h1> hello </h1>

<script type="text/javascript" >
var hr = new XMLHttpRequest();
//alert(typeof hr);

hr.overrideMimeType('text/xml');

hr.onreadystatechange = process;

function userlogin(){
    var rnumber = document.getElementById('rnumber').value;
    //hr.open('get', '/blog/regist/?username='+uname,true);
    //hr.send(null);
    
    hr.open('post','/regist/',true);
    hr.setRequestHeader("Content-type","application/x-www-form-urlencoded");
    hr.send('rnumber='+rnumber);
}
function process(){
    if (hr.readyState == 4){
     var user = document.getElementById('user');
     //alert(hr.responseText);
     user.innerHTML = hr.responseText;
     //alert(hr.reasponseText);
    }
}


</script>
</body>

crmapp/templates/rinstall1.html
<form name="form1" action="/rinstall" method="post" >{% csrf_token %}
<input type="text" name="number" id="number" onblur="userlogin()">
</form>
<div id='user'>
<div>

<!--<form name="form2" action="" method="post" >{% csrf_token %}
<table>
{%if routing.gateway%}
<strong>gateway:</strong>{{routing.gateway}}<br/>
{% endif %}
{% if routing.password%}
<strong>password:</strong>{{routing.password}}<br/>
{% endif %}
{{rf.is_main}}
{{rf.mac}}
{{rf.lanip}}
{{rf.port}}
</table>
{{routing.mac}}
<input type="submit" value="sub">
<form>-->
<script>
var hr = new XMLHttpRequest();
hr.overrideMimeType('text/xml');

hr.onreadystatechange = process;


function userlogin(){
    var number = document.getElementById('number').value;
    //hr.open('get', '/blog/regist/?username='+uname,true);
    //hr.send(null);
    
    hr.open('post','/Routing_install',true);
    hr.setRequestHeader("Content-type","application/x-www-form-urlencoded");
    hr.send('number='+number);

function process(){
    if (hr.readyState == 4){
     var user = document.getElementById('user');
     alert(hr.responseText);
     user.innerHTML = hr.responseText;
     //alert(hr.reasponseText);
    }
}






//var number=document.getElementById('id_number');
//var gateway=document.getElementById('id_gateway');
//var password=document.getElementById('id_password');
//number.style.display='none';
//gateway.style.display='none';
//password.style.display='none';
//var arr=document.getElementsByTagName("label");
//  for(i=0;i<arr.length;i++)
//              {
//                     var forvalue=arr[i].getAttributeNode("for").value;
//                     if(forvalue==number.id)
//                     {
//                           arr[i].style.display='none';
//                     }
//                     if(forvalue==gateway.id)
//                     {
//                           arr[i].style.display='none';
//                     }
//                     if(forvalue==password.id)
//                     {
//                           arr[i].style.display='none';
//                     }
//              }
</script>
<!--<form name="form2" action="" method="post" >{% csrf_token %}
<table>
<tr>
<label>网关ID:</label>{{gateway}}
</tr>
<br />
<tr>
<label>路由器密码:</label>{{rpassword}}
</tr>
<br />
是否是主路由:{% if is_main %}<select name="im">
<option>{{is_main}}</option>
<option>False</option>
</select>
{% endif %}
<br />
<br />
mac地址:{% if mac %}<input type="text" value="{{mac}}"><br/>
{% endif %}
<br />
SSID:{% if ssid %}<input type="text" value="{{ssid}}"><br/>
{% endif %}
<br />
LANIP:{% if lanip %}<input type="text" value="{{lanip}}"><br/>
{% endif %}
<br />
端口:{% if port %}<input type="text" value="{{port}}">
{% endif %}
</table>
<input type="submit" value="submit">
{{business}}
{{shopname}}
{{tag}}
{{district}}
</form>-->

crmapp/templates/routinginstall.html
{{router}}
{{router.condition}}
{{router.installtime}}

crmapp/templates/show_busy.html
<table>
<tr>
<td>商家编号</td>
<td>商店名称</td>
<td>门店名称</td>
<td>所在地区</td>
<td>地址</td>
<td>状态</td>
<td>安装人</td>
<td>已安装路由</td>
<td>操作</td>
<td>备注</td>

</tr>

{% for busy in business %}
<tr>

<td>{{ busy.number }}</td>
<td>{{ busy.name }}</td>
<td>{{ busy.shopname }}</td>
<td>{{ busy.district }}</td>
<td>{{ busy.address }}</td>
</td>
<td>
<a href='/direct/{{busy.id}}'>指定安装人员</a>

</td>
<td>{{ busy.remarks }}</td>
<td>
<select>
{% for r in busy.routing_set.all %}
{% if r.condition == "installed" %}
<option>{{r}}</option>
{% endif %}
{% endfor%}
</select>
</td>
</tr>
{% endfor %}
</table>

crmapp/templates/show_info.html
路由编号：{{router.number}}<br />
路由ssid:{{router.ssid}}<br />
商家:{{router.business}}<br />
商家商圈:{{router.business.district}}<br />
商家地址:{{router.business.address}}<br />
合同编号{{router.business.cooperinfo}}<br />
合同图片<img src='/media/{{router.business.cooperinfo.cooperImg}}' height=150 width=200>
<a href="/routing_install/{{router.id}}/{{user.id}}">确定</a>

crmapp/templates/show_router.html
<table>
<tr>
<td>路由编号</td>
<td>路由密码</td>
<td>路由mac</td>
<td>路由ssid</td>
<td>状况</td>
<td>操作</td>
<td>安装人</td>
<td>安装时间</td>
<td>备注</td>

</tr>

{% for router in routers %}
<tr>

<td>{{ router.number }}</td>
<td>{{ router.password }}</td>
<td>{{ router.mac }}</td>
<td>{{ router.ssid }}</td>
<td>
{% if router.condition == "not_installed" %}
未安装
{% else %}
已安装
{% endif %}
</td>
{% if router.condition == "not_installed" %}
<td>
<a href='/show_info/{{router.id}}/{{user.id}}'>安装</a>
</td>
<td>---</td>
<td>---</td>
{% else %}
<td>---</td>
<td>{{router.installor}}</td>
<td>{{router.installtime}}</td>
{% endif %}
<td>{{ router.remarks }}</td>
</tr>
{% endfor %}
</table>

crmapp/templates/tag_add.html
<script>
function id_to_windowname(text) {
    text = text.replace(/\./g, '__dot__');
    text = text.replace(/\-/g, '__dash__');
    return text;
}

function showAddAnotherPopup(triggeringLink) {
    var name = triggeringLink.id.replace(/^add_/, '');
    name = id_to_windowname(name);
    href = triggeringLink.href
    //alert(href);
    if (href.indexOf('?') == -1) {
        href += '?_popup=1';
    } else {
        href  += '&_popup=1';
    }
    var win = window.open(href, name, 'height=500,width=800,resizable=yes,scrollbars=yes');
    win.focus();
    return false;
}
</script>
<form action="" method="POST"> {% csrf_token %}
<table>
{{tf.as_table}}
<a href="tag_add/" class="add-another" id="add_id_tag" onclick="return showAddAnotherPopup(this);">添加经营内容</a><br/>
</table>
<input type="submit" value="确定">

</form>

crmapp/templates/ulogin.html
<form action="" method="POST"> {% csrf_token %}
<table>
{{lf.as_table}}
</table>
<input type="submit" value="确定">
</form>

crmapp/templates/user_add.html
<form action="" method="post" enctype="multipart/form-data"> {% csrf_token %}
<table>
{{uf.as_table}}
</table>
<a href='/display_meta'>d</a>
<input type="submit" value="提交">
<a href='/logout'>注销</a>
</form>

crmapp/templates/user_home.html
{{user}}<br />
{{user.maintainer.name}}<br />
{{maintainer.identity}}<br />
{{user.maintainer.receive__mail.all}}
{% for r in maintainer.installor.all %}
{{r}}<br />
{% endfor %}

crmapp/templates/write_mail.html
<form action="" method="post" enctype="multipart/form-data"> {% csrf_token %}
<table>
{{mf.as_table}}
</table>
<input type="submit" value="提交">
</form>